Finastra/finastra-design-system

themes/angular-theme/package.json
=> bugfix(angular-theme): cleanup dependencies

tools/schematics/angular-component/index.ts, tools/schematics/angular-component/schema.json, tools/schematics/angular-component/schema.ts
As per it's description.
Cleanup `schema.json` and `schema.ts` to follow only allowed component properties and removed some useless comments.
=> bugfix(angular-component-schematic): fix & clean up schematic

themes/angular-theme/lib/avatar/_avatar-theme.scss, themes/angular-theme/lib/breadcrumb/_breadcrumb-theme.scss, themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss, themes/angular-theme/lib/chips/_chips-theme.scss, themes/angular-theme/lib/core/typography/_typography.scss, themes/angular-theme/lib/list/_list-theme.scss
update typography scales to reflect changes made in the Design System.
=> feat(typography): update typography scales

themes/angular-theme/_uxg-app-theme.scss, themes/angular-theme/lib/core/theming/_all-theme.scss, themes/angular-theme/lib/icon/_icon-base.scss, themes/angular-theme/lib/icon/_icon-theme.scss
=> fix(icon): add uxg icons sizes and colors in angular theme

themes/angular-theme/lib/chips/_chips-theme.scss
=> fix(chips-style): remove icon did not have hover style in selected state

themes/angular-theme/lib/chips/_chips-theme.scss, themes/angular-theme/lib/core/typography/_typography.scss
=> feat(typography): add new scale

libs/angular-components/core/package.json, libs/angular-components/filter/filter-tags/ng-package.json, libs/angular-components/filter/filter-tags/package.json, libs/angular-components/filter/filter-tree/ng-package.json, libs/angular-components/filter/filter-tree/package.json, libs/angular-components/global-search/package.json, libs/angular-components/package.json, libs/angular-components/popover/package.json, libs/angular-components/scroll-to-top/package.json, libs/angular-components/table/package.json, package.json, themes/angular-theme/lib/badge/_badge-base.scss, themes/angular-theme/lib/badge/_badge-theme.scss, themes/angular-theme/lib/chips/_chips-theme.scss, themes/angular-theme/lib/core/typography/_typography.scss, themes/angular-theme/package.json, tools/devkit/package.json
Closed by mistake #51
Creating this and merging it.
=> feat(unit-testing): added coverage collection and printing joined report

apps/angular-test-app/src/app/components/repeater-demo/repeater-card-advanced-example/repeater-card-advanced-example.component.ts, apps/angular-test-app/src/app/components/repeater-demo/repeater-card-chart-example/repeater-card-chart-example.component.ts, apps/angular-test-app/src/app/components/repeater-demo/repeater-card-example/repeater-card-example.component.ts, apps/angular-test-app/src/app/components/repeater-demo/repeater-demo.component.html
Fix buid prod issue caused by repeater
=> bugfix(repeater): fix issue when building for production

libs/angular-components/core/src/filter/filter.models.ts, libs/angular-components/filter/filter-tags/src/_filter-tags.theme.scss, libs/angular-components/filter/filter-tags/src/filter-tags.component.html, libs/angular-components/filter/filter-tags/src/filter-tags.component.ts, libs/angular-components/filter/filter-tree/src/filter-tree.component.html, libs/angular-components/filter/filter-tree/src/filter-tree.component.scss, libs/angular-components/filter/filter-tree/src/filter-tree.component.spec.ts, libs/angular-components/filter/filter-tree/src/filter-tree.component.ts
general:
- fix inputs not being inherited from base class
tree filter:
- compact spacing
- removed unnecessary divider lines between categories
- ripples and icon wrappers are no longer cut-off
- bring back checkbox ripples
- better and smoother expand/collapse animation (+ Angular way)
tags filter:
- add search icon as input suffix + align + color primary
- keep only placeholder (no need for floating label)
=> feat(filters): improve + fix filters

libs/angular-components/ng-package.json, libs/angular-components/package.json
to fix stackblitz's APIs limitation
=> fix(angular-components): add elasticlunr as an explicit dependency

apps/angular-test-app/src/app/components/repeater-demo/repeater-demo.component.html, libs/angular-components/repeater/src/repeater.component.spec.ts, libs/angular-components/repeater/src/repeater.component.ts
=> feature(repeater) Add default selected items

package-lock.json, themes/angular-theme/lib/breadcrumb/_breadcrumb-base.scss
=> fix(theme): child with margin in breadcrumb element.

themes/angular-theme/lib/core/theming/_palette.scss
Implement the design guidelines provided here -> https://design.fusionfabric.cloud/foundations/colors
=> fix(colors): add shades of secondary colors

libs/angular-components/filter/filter-tree/src/filter-tree.component.scss
=> fix(filter-tree): remove wrong paddings

scripts/release.js
Change release script to also bump package-lock files' version.
=> fix(script): bump version for package-lock too.

apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.ts, libs/angular-components/filter/filter-tags/src/filter-tags.component.html, libs/angular-components/filter/filter-tags/src/filter-tags.component.ts, libs/angular-components/filter/filter-tree/src/filter-tree.component.html, libs/angular-components/filter/filter-tree/src/filter-tree.component.scss, libs/angular-components/filter/filter-tree/src/filter-tree.component.spec.ts, libs/angular-components/filter/filter-tree/src/filter-tree.component.ts
Set initial state of filters in dataSource.
=> feat(filters): filter improvements

themes/angular-theme/lib/button-toggle/_button-toggle-base.scss, themes/angular-theme/lib/button/_button-base.scss, themes/angular-theme/lib/chips/_chips-base.scss, themes/angular-theme/lib/chips/_chips-theme.scss, themes/angular-theme/lib/core/typography/_typography.scss, themes/angular-theme/lib/icon/_icon-base.scss
=> feat(chips): update chips sizes to comply with Sketch design

libs/angular-components/table/src/table.component.ts
When data was updated pagination was lost
=> bugfix(table): fix table pagination when data is updated

apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.html, apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.scss, themes/angular-theme/lib/button-toggle/_button-toggle-base.scss, themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss
=> feat(button-toggle): update button toggle to comply with design

themes/angular-theme/lib/button-toggle/_button-toggle-base.scss, themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss
=> fix(toggle-button): fix typography and icon margin

libs/angular-components/filter/filter-tags/src/filter-tags.component.scss, libs/angular-components/popover/src/popover.component.html, libs/angular-components/popover/src/popover.component.scss, themes/angular-theme/lib/button-toggle/_button-toggle-base.scss, themes/angular-theme/lib/chips/_chips-theme.scss
FIxed alignment on tags:
Fixed popover style:
Changed dense chips font weight.
=> fix(theme): fix tags, popover and chips weight

themes/angular-theme/lib/button/_button-theme.scss, themes/angular-theme/lib/icon/_icon-theme.scss
The changes were applied both to the icon and to the button.
=> fix(icon): gradient background removed for IE11

apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.html, themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss
- fix hover artifact on selected button
- fix left-border on buttons (it needed a hard color, not an alpha channel one)
- reduced opacity of disabled button (both text and icon), because it was not very distinguishable from the normal non-selected style
=> fix(theme): fix minor issues with button-toggle

apps/angular-test-app/src/app/components/vector-map-demo/vector-map-demo.component.html, apps/angular-test-app/src/app/components/vector-map-demo/vector-map-demo.component.scss, libs/angular-components/vector-map/src/vector-map.component.ts, themes/angular-theme/lib/core/theming/_palette.scss
Fix issue for vector map tooltip.
=> Fix: vector-map tooltip #152

apps/angular-test-app/src/app/components/table-demo/table-demo.component.html, apps/angular-test-app/src/app/components/table-demo/table-demo.component.ts, libs/angular-components/table/src/table.component.ts
Custom pagination was lost when paginating and replace by default one
=> bugfix(table): custom pagination was lost when paginating

libs/angular-components/chart/README.md
=> Chart: Add README for chart

libs/angular-components/skeleton-text/src/_skeleton-text.theme.scss
=> fix(skeleton): fix background losing size

apps/angular-test-app/src/app/components/expandable-table-demo/expandable-table-demo.component.ts, libs/angular-components/expandable-table/src/expandable-table.component.ts
fix row id that was equal to label
=> bugfix(expandable-table): fix row id equal to row label

.github/workflows/pr-build.yml, libs/angular-components/avatar/src/avatar.component.ts, libs/angular-components/filter/multiselect-tags/src/multiselect-tags.component.spec.ts, libs/angular-components/filter/multiselect-tags/src/multiselect-tags.component.ts, libs/angular-components/user-profile-menu/src/user-profile-menu.component.spec.ts, libs/angular-components/user-profile-menu/src/user-profile-menu.module.spec.ts, nx.json
Fixes #187 
Used https://github.com/nrwl/nx/issues/1624#issuecomment-543296956 to get base SHA
=> fix(project): fix github workflows affected tasks

package-lock.json, package.json
Added `pre-commit` hooks for linting & formatting
1. Committing will now fail if you have linting issues
2. All changers you add will be formatted and appended to the staged changes.
Due to the nature of how this works, please **DO NOT** edit any files when hooks are working.
=> feat(project): add pre-commit hook to lint & format

themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss
=> bugfix(theme): fix toggle group color in dark mode

apps/angular-test-app/src/app/components/user-profile-menu-demo/user-profile-menu-demo-component.component.html, libs/angular-components/user-profile-menu/src/user-profile-menu.component.html, libs/angular-components/user-profile-menu/src/user-profile-menu.component.ts, libs/angular-components/user-profile-menu/src/user-profile-panel.component.html, libs/angular-components/user-profile-menu/src/user-profile-panel.component.ts, themes/angular-theme/lib/block/_title-base.scss
Added MatMenuTrigger in component in order to programmatically open and close panel.
=> feature(user-profile-menu): Added MatMenuTrigger

libs/angular-components/filter/filter-tags/index.ts, libs/angular-components/filter/filter-tags/src/_filter-tags.theme.scss, libs/angular-components/filter/filter-tags/src/filter-tags.component.html, libs/angular-components/filter/filter-tags/src/filter-tags.component.scss, libs/angular-components/filter/filter-tags/src/filter-tags.component.spec.ts, libs/angular-components/filter/filter-tags/src/filter-tags.component.ts, libs/angular-components/filter/filter-tags/src/filter-tags.module.ts, libs/angular-components/filter/filter-tags/src/highlight.pipe.spec.ts, libs/angular-components/filter/filter-tags/src/highlight.pipe.ts
- allow full text search within the tag
- don't add the chip if not in the list
- highlight search term
=> fix(filter): improve filter tags

apps/angular-test-app/src/app/components/ui-elements-demo/ui-elements-demo.component.html, themes/angular-theme/lib/select/_select-base.scss
=> bugfix(select): fix select arrow

apps/angular-test-app/src/app/components/table-demo/table-demo.component.ts, themes/angular-theme/lib/table/_table-base.scss
=> fix mat-icons positioning in table actions

angular.json, apps/angular-test-app/src/app/app.module.ts, apps/angular-test-app/src/app/components/search-input-demo/search-input-demo.component.html, apps/angular-test-app/src/app/components/search-input-demo/search-input-demo.component.scss, apps/angular-test-app/src/app/components/search-input-demo/search-input-demo.component.ts, apps/angular-test-app/src/app/nested-routes.ts, libs/angular-components/search-input/index.ts, libs/angular-components/search-input/jest.config.js, libs/angular-components/search-input/ng-package.json, libs/angular-components/search-input/package.json, libs/angular-components/search-input/src/search-input.component.html, libs/angular-components/search-input/src/search-input.component.scss, libs/angular-components/search-input/src/search-input.component.ts, libs/angular-components/search-input/src/search-input.module.ts, libs/angular-components/search-input/test-setup.ts, libs/angular-components/search-input/tsconfig.json, libs/angular-components/search-input/tsconfig.lib.json, libs/angular-components/search-input/tsconfig.spec.json, libs/angular-components/search-input/tslint.json, nx.json, tsconfig.json
=> feat: implement search-input component

angular.json, apps/angular-test-app/src/app/app.module.ts, apps/angular-test-app/src/app/components/breadcrumb-demo/breadcrumb-demo.component.html, apps/angular-test-app/src/app/components/breadcrumb-demo/breadcrumb-demo.component.scss, apps/angular-test-app/src/app/components/breadcrumb-demo/breadcrumb-demo.component.ts, apps/angular-test-app/src/app/components/ui-elements-demo/ui-elements-demo.component.html, apps/angular-test-app/src/app/nested-routes.ts, libs/angular-components/breadcrumb/index.ts, libs/angular-components/breadcrumb/jest.config.js, libs/angular-components/breadcrumb/ng-package.json, libs/angular-components/breadcrumb/package.json, libs/angular-components/breadcrumb/src/breadcrumb.component.html, libs/angular-components/breadcrumb/src/breadcrumb.component.ts, libs/angular-components/breadcrumb/src/breadcrumb.module.ts, libs/angular-components/breadcrumb/src/breadcrumb.ts, libs/angular-components/breadcrumb/test-setup.ts, libs/angular-components/breadcrumb/tsconfig.json, libs/angular-components/breadcrumb/tsconfig.lib.json, libs/angular-components/breadcrumb/tsconfig.spec.json, libs/angular-components/breadcrumb/tslint.json, nx.json, themes/angular-theme/lib/breadcrumb/_breadcrumb-base.scss, themes/angular-theme/lib/breadcrumb/_breadcrumb-theme.scss, tsconfig.json
=> feat(breadcrumb): add component

libs/angular-components/global-search/src/_global-search.theme.scss, libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.html, libs/angular-components/global-search/src/global-search.component.scss
=> feat(accessibility): global search AA standard

libs/angular-components/changelog/src/changelog.component.html, libs/angular-components/changelog/src/changelog.component.scss, libs/angular-components/changelog/src/changelog.component.ts
Display changelog version left: `<uxg-changelog [title]="'FDS'" [changelog]="changelog" displayVersion="left"></uxg-changelog>`
Display changelog version top: `<uxg-changelog [title]="'FDS'" [changelog]="changelog" displayVersion="top"></uxg-changelog>`
Display no version: `<uxg-changelog [title]="'FDS'" [changelog]="changelog" displayVersion="none"></uxg-changelog>`
=> feat(changelog): Changelog display options for version

libs/angular-components/global-search/src/_global-search.theme.scss, libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay-config.ts, libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.html, libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.ts, libs/angular-components/global-search/src/global-search.component.scss, libs/angular-components/global-search/src/global-search.component.ts
New empty template added for the global search
=> feat(global-search): improvements

libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.html, libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.ts, libs/angular-components/global-search/src/global-search.component.ts
- expose close from main component
- show empty search template instead of no results if search value is blank
=> feat(global-search): more improvements

libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.html, libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.ts, libs/angular-components/global-search/src/global-search.component.ts
This PR aim is to add search history to the global search.
=> feat(global-search): Recent searches

apps/angular-test-app/src/app/components/foundations-demo/foundations-demo.component.html, themes/angular-theme/lib/core/theming/_all-theme.scss, themes/angular-theme/lib/core/theming/_color-utility.scss
adding some utility classes to color texts:
.uxg-text-primary
.uxg-text-accent or .uxg-text-secondary
.uxg-text-warn or .uxg-text-error
=> feat(color): providing utility classes for text color

themes/angular-theme/lib/button/_button-theme.scss
=> fix(button): bring back ripple effect on buttons

libs/angular-components/filter/filter-tree/src/filter-tree.component.ts
This feature updates the configuration of the filter-tree allowing a single selection mode.
=> feat(filter-tree): configurable selection mode

libs/angular-components/filter/filter-toggle/src/filter-toggle.component.ts
clearSelection function should emit change.
=> fix(filter-toggle): clear selection not emitting change

libs/angular-components/filter/filter-tags/src/filter-tags.component.html, libs/angular-components/filter/filter-tags/src/filter-tags.component.ts
Fix accessibility issue when having multiple filter-tag components.
=> bugfix(filter-tags): configurable aria-label

themes/angular-theme/lib/expansion/_expansion-base.scss, themes/angular-theme/lib/expansion/_expansion-theme.scss
remove reference to class .uxg-dark-theme in expansion SCSS.
=> fix(expansion): remove ref to uxg-dark-theme class

libs/angular-components/filter/filter-tags/src/filter-tags.component.html, libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.html
@adrian-apetrei  or @Octavians98  can you have a look? btw @ttalbot may I receive permission to be able to push changes without creating fork
=> fix(components): aria changes on global search & filter tags

apps/angular-test-app/src/app/components/vector-map-demo/vector-map-demo.component.html, apps/angular-test-app/src/app/components/vector-map-demo/vector-map-demo.component.ts, libs/angular-components/chart/src/chart.component.html, libs/angular-components/vector-map/src/vector-map.component.html, libs/angular-components/vector-map/src/vector-map.component.spec.ts
Changing plotly_click event to plotlyClick for consistence among other event names
https://github.com/plotly/angular-plotly.js/blob/master/CHANGELOG.md#changed-2
=> fix(components): Plotly click event

libs/angular-components/filter/filter-group/src/filter-group.component.html
Added badge size and color
Removed header animation
=> bugfix(filter-group): Set badge size and fix header size

themes/angular-theme/lib/expansion/_expansion-theme.scss, themes/angular-theme/lib/menu/_menu-theme.scss, themes/angular-theme/lib/table/_table-theme.scss, themes/angular-theme/lib/toolbar/_toolbar-theme.scss
=> bugfix(theme): color opacity

libs/angular-components/table/src/table.component.scss, themes/angular-theme/lib/table/_table-base.scss
=> refactor(table): remove unused styles

apps/fds-test-app/src/styles.scss, themes/fds-theme/_index.scss, themes/fds-theme/color/README.mdx, themes/fds-theme/color/_dark.scss, themes/fds-theme/color/_index.scss, themes/fds-theme/color/_light.scss
add on-gradient color for accessible text over gradient.
=> fix(fds): add on-gradient color

.storybook/preview-head.html, tools/dev-server/view/layout.html
link to spartan open font was missing
=> bugfix(fds-typo): link to Spartan

themes/fds-theme/color/README.mdx, themes/fds-theme/color/_dark.scss, themes/fds-theme/color/_light.scss
Add a variable for primary at opacity 8%
=> feature(fds-colors): add primary lighter color

apps/fds-test-app/src/styles.scss, themes/fds-theme/color/README.mdx, themes/fds-theme/color/_dark.scss, themes/fds-theme/color/_light.scss, themes/fds-theme/color/_mixins.scss
adding support for gradient text like so:
```SCSS
@include fds.text-color(gradient);
@include fds.text-color(gradient-horizontal);
@include fds.text-color(gradient-vertical);
```
=> feat(fds): add text gradient

libs/web-components/card/stories/card.stories.mdx
=> fix(card-story): add missing code snippet

.storybook/preview-body.html, libs/web-components/search-input/src/styles.scss
Use fds custom properties to theme search input wc
=> fix(fds-search-input): use fds theme

libs/web-components/divider/src/styles.scss, libs/web-components/divider/stories/divider.stories.mdx
- Use fds custom props in divider style
- Add more examples in storybook doc
=> fix(fds-divider): improve storybook doc

apps/fds-test-app/src/styles.scss, themes/fds-theme/_index.scss, themes/fds-theme/spacing/_index.scss, themes/fds-theme/spacing/_mixins.scss
Add mixins to support horizontal and vertical margin.
=> feat(fds): add x and y margin mixin

.github/workflows/storybook.yml
=> chore(workflows): update storybook.yml

.github/workflows/pr-build.yml
ignore .github folder when running Angular PR CI
=> chore(action): ignore .github folder

themes/fds-theme/typography/_mixins.scss, themes/fds-theme/typography/_variables.scss
Add support for mdc typo custom properties
=> fix(fds-typo): fds<->mdc mapping

.github/workflows/codecov.yml, .gitpod.yml, README.md, libs/web-components/README.md, libs/web-components/button/README.md, libs/web-components/card/README.md, libs/web-components/divider/README.md, libs/web-components/logo/README.md, libs/web-components/search-input/README.md
=> ✨ Enhance web component documentation

.storybook/preview-body.html, .vscode/settings.json, libs/web-components/avatar/src/styles.scss, libs/web-components/button/demo/index.html, libs/web-components/button/src/button.ts, libs/web-components/button/src/styles.scss, libs/web-components/button/stories/button.stories.mdx
=> fix(fds-button): add fullwidth property

themes/fds-theme/color/_dark.scss, themes/fds-theme/color/_light.scss, themes/fds-theme/color/_mixins.scss
Before:
`--fds-gradient: linear-gradient(#694ED6, #C137A2);`
After :
`--fds-gradient: linear-gradient(var(--fds-primary),var(--fds-secondary));`
=> fix(fds-gradient): gradient based on css vars

themes/fds-theme/color/_dark.scss
Semantic colors were not correct in dark theme.
=> fix(color): use proper semantic colors

angular.json, libs/web-components/switch/.eslintrc.json, libs/web-components/switch/.npmignore, libs/web-components/switch/README.md, libs/web-components/switch/demo/index.html, libs/web-components/switch/package.json, libs/web-components/switch/src/styles.scss, libs/web-components/switch/src/switch.ts, libs/web-components/switch/stories/switch.stories.ts, libs/web-components/switch/test/switch.test.ts, libs/web-components/switch/tsconfig.json, libs/web-components/tsconfig.json, package-lock.json
=> feature(wc): fds switch

tools/generators/web-component/files/README.md
Generate play bagde automatically
=> fix(wc-generator): generate play badge

.github/CODEOWNERS
Update code owners for web components files
=> fix(.github): update code owners

.storybook/main.js, package-lock.json, package.json
Get accessibility results built in storybook tabs
=> feat(wc): add accessibility addon for storybook

apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.html, apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.ts, apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.sample-data.ts, apps/angular-test-app/src/app/components/ui-elements-demo/ui-elements-demo.component.ts, libs/angular-components/filter/filter-tags/src/_filter-tags.theme.scss, libs/angular-components/filter/filter-tags/src/filter-tags.component.html, libs/angular-components/filter/filter-tags/src/filter-tags.component.scss, libs/angular-components/filter/filter-tags/src/filter-tags.component.ts, libs/angular-components/filter/filter-tags/src/filter-tags.module.ts
=> feat(filter): Multiselect filter tags

themes/angular-theme/lib/core/theming/_all-theme.scss
=> fix(typo): visible gradient text selection

apps/angular-test-app/src/app/components/wizard-demo/wizard-demo.component.html, libs/angular-components/wizard/src/wizard-page/wizard-page.component.ts, libs/angular-components/wizard/src/wizard.component.html
introduce "uxgWizardPageCompleted" input on wizard page to allow pages to be manually marked as completed or not.
Not setting this will fallback to existing behavior.
=> feat(wizard): allow pages to be marked as completed

libs/web-components/app-card/src/styles.scss
=> fix(logo): hide overflow and fix aspect ratio

README.md
Following some users' feedback we clarify the difference between:
- web components content
- Angular ressources
plus removing old content no longer relevant.
=> doc: better separation of content in home readme

libs/web-components/charts/demo/index.html, libs/web-components/charts/src/apexcharts.ts, libs/web-components/charts/src/pie-chart.ts
=> fix(wc): Pie/Donut chart stop working past 7 values

libs/web-components/charts/src/donut-chart.ts, themes/fds-theme/color/_dark.scss
=> fix(wc): sequential palette is inverted in dark theme

libs/web-components/autocomplete/src/styles.scss
=> bugfix: adapt autocomplete to its container

libs/web-components/select/demo/index.html, libs/web-components/select/src/select.ts, libs/web-components/select/src/styles.scss, libs/web-components/select/stories/select.stories.ts, libs/web-components/textarea/demo/index.html, libs/web-components/textarea/src/styles.scss, libs/web-components/textarea/src/textarea.ts, libs/web-components/textarea/stories/textarea.stories.ts
=> bugfix#820-821 use new textfield guideline

libs/web-components/autocomplete/stories/autocomplete.stories.ts
=> fix:update storybook for autocomplete

libs/web-components/icon-bar/demo/index.html, libs/web-components/icon-bar/src/icon-bar-item.scss, libs/web-components/icon-bar/src/icon-bar-item.ts, libs/web-components/icon-bar/src/icon-bar.scss, libs/web-components/icon-bar/src/icon-bar.ts, libs/web-components/icon-bar/stories/icon-bar.stories.ts, libs/web-components/icon-button/src/styles.scss
=> bugfix#847 fix item bar size

scripts/wca-to-storybook.js
wc storybook build script failed on Windows
=> fix(wca): script for Windows

libs/web-components/get-started/README.md, libs/web-components/get-started/stories/get-started.stories.ts
=> [WC] Feature Get Started Pattern

libs/web-components/button/src/base-styles.scss
=> Fix(fds-button): disabled button triggering click events

.storybook/theme-dark.js, .storybook/theme-light.js
=> feat(sb): update logo in Storybook

libs/web-components/charts/demo/index.html, libs/web-components/charts/package.json, libs/web-components/charts/src/apexcharts.ts, libs/web-components/charts/src/index.ts, libs/web-components/charts/src/radial-bar-chart-styles.scss, libs/web-components/charts/src/radial-bar-chart.ts, libs/web-components/charts/stories/radial-bar-charts.stories.ts
=> feature(charts) new radial-bar

angular.json, apps/angular-test-app/src/app/components/entity-menu-demo/entity-menu-demo.component.html, apps/angular-test-app/src/app/components/entity-menu-demo/entity-menu-demo.component.scss, apps/angular-test-app/src/app/components/entity-menu-demo/entity-menu-demo.component.ts, libs/angular-components/entity-menu/src/entity-menu.component.html, libs/angular-components/entity-menu/src/entity-menu.component.scss, libs/angular-components/entity-menu/src/entity-menu.component.ts
Allow entity menu to hold more than 9 items
=> MAFTC-16274 allow entity menu to hold infinite data

libs/web-components/data-table/src/data-table-styles.scss, libs/web-components/stepper/src/base-stepper.ts, libs/web-components/stepper/src/v-styles.scss, libs/web-components/wizard/src/styles.scss, libs/web-components/wizard/src/wizard-page.scss, libs/web-components/wizard/src/wizard.ts, libs/web-components/wizard/stories/wizard.stories.ts, package-lock.json
=> bugfix(fds-wizard): sticky and full width action bar 

themes/fds-theme/color/_dark.scss, themes/fds-theme/color/_light.scss, themes/fds-theme/color/color.stories.mdx
adding:
- warning
- info
- surface-success
- surface-error
- surface-warning
- surface-info
- outline-success
- outline-error
- outline-warning
- outline-info
=> feat(color): adding semantic tokens

libs/web-components/autocomplete/README.md, libs/web-components/autocomplete/demo/index.html, libs/web-components/autocomplete/stories/autocomplete.stories.ts, libs/web-components/data-table/src/pagination/data-table-pagination-styles.scss, libs/web-components/get-started/stories/get-started.stories.ts, libs/web-components/global-nav/stories/global-nav.stories.ts, libs/web-components/launchpad/package.json, libs/web-components/launchpad/src/launchpad.ts, libs/web-components/launchpad/src/styles.scss, libs/web-components/launchpad/test/launchpad.test.ts, libs/web-components/list/demo/index.html, libs/web-components/list/stories/list.stories.ts, libs/web-components/menu-trigger/package.json, libs/web-components/menu/README.md, libs/web-components/menu/demo/index.html, libs/web-components/menu/stories/menu.stories.ts, libs/web-components/select/README.md, libs/web-components/sidenav/stories/sidenav.stories.ts, libs/web-components/status-message/README.md, libs/web-components/status-message/stories/status-messages.stories.ts, libs/web-components/user-profile/demo/index.html, libs/web-components/user-profile/package.json, libs/web-components/user-profile/src/styles.scss, libs/web-components/user-profile/src/user-profile.ts, libs/web-components/user-profile/stories/user-profile.stories.ts, libs/web-components/user-profile/test/user-profile.test.ts, package-lock.json, tools/dev-server/view/css/styles.css, tools/dev-server/view/layout.html, tools/dev-server/view/list-components.html
replacing a bunch of:
- mwc-icon with fds-icon
- mwc-menu with fds-menu
- mwc-button with fds-button
- mwc-list with fds-list
=> feat(wc): replace mwc by fds when available

libs/web-components/wizard/src/styles.scss
=> fix(fds-wizard): remove padding right from wizard content

apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.component.html, apps/angular-test-app/src/app/components/search-input-demo/search-input-demo.component.html, libs/angular-components/filter/filter-tags/src/filter-tags.component.html, libs/angular-components/filter/filter-tags/src/filter-tags.component.ts, libs/angular-components/search-input/src/search-input.component.html, libs/angular-components/search-input/src/search-input.component.scss, libs/angular-components/search-input/src/search-input.component.ts
Add support for changing appearance for angular components:
- filter panel
- search input
=> Add support for changing appearance for angular components

angular.json, apps/angular-test-app/src/app/components/table-demo/table-demo.component.html, apps/angular-test-app/src/app/components/table-demo/table-demo.component.ts, libs/angular-components/table/src/table.component.html, libs/angular-components/table/src/table.component.ts
Add sort "injection" possibility to the table
=> add sort injection

libs/web-components/icon/src/styles.scss
=> fix(icon): change large size to 32px

apps/angular-test-app/src/app/components/filter-panel-demo/filter-panel-demo.sample-data.ts, libs/angular-components/filter/filter-tags/src/filter-tags.component.ts
=> feat(uxg-filter-tags): Add "value" parameter

libs/angular-components/table/src/table.component.ts
fix sort injection I've implemented
=> fix sort injection

.vscode/settings.json, libs/web-components/breadcrumb/README.md, libs/web-components/breadcrumb/src/breadcrumb.ts, libs/web-components/breadcrumb/src/styles.scss, libs/web-components/breadcrumb/stories/breadcrumb.stories.ts, libs/web-components/breadcrumb/test/breadcrumb.test.ts
Breadcrumb now expect label + link and are more semantically accessible
#943
=> feat(wc:breadcrumb): :sparkles: Breadcrumb v2

libs/angular-components/table/src/table.component.ts
fix pagination when sorting is external
=> fix pagination when Pagination is external

libs/web-components/autocomplete/src/autocomplete.ts, libs/web-components/autocomplete/src/styles.scss
=> fix(fds-autocomplete): menu not displaying

libs/web-components/charts/src/radial-bar-chart-styles.scss, libs/web-components/charts/src/radial-bar-chart.ts, libs/web-components/charts/stories/radial-bar-charts.stories.ts
=> fix(fds-radial-bar ): support multiple sizes

package.json, scripts/pre-angular-release.js
=> feat(scripts): :hammer: Prevent launch of angular release script if on master branch

libs/web-components/button-toggle-group/src/button-toggle-group.ts, libs/web-components/button-toggle-group/src/button-toggle/styles.scss, libs/web-components/button-toggle-group/stories/button-toggle-group.stories.ts, libs/web-components/button-toggle-group/test/button-toggle-group.test.ts, libs/web-components/button/src/base-styles.scss
update selection size and position when fonts are loaded.
use 'selected-index' attribute name
Add hover and focus states
=> fix(toggle-group): update selection and hover styles

.vscode/settings.json, libs/web-components/button-toggle-group/stories/button-toggle-group.stories.ts, libs/web-components/charts/stories/donut-charts.stories.ts, libs/web-components/charts/stories/pie-charts.stories.ts, libs/web-components/charts/stories/radial-bar-charts.stories.ts, libs/web-components/circular-progress/stories/circular-progress.stories.ts, libs/web-components/linear-progress/stories/linear-progress.stories.ts, libs/web-components/search-input/stories/search-input.stories.ts
=> ci(storybook): :wrench: Remove indeterminate stories from chromatic snapshots

libs/web-components/data-table/README.md, libs/web-components/data-table/demo/index.html, libs/web-components/data-table/src/data-table-base.ts, libs/web-components/data-table/src/data-table-with-pagination.ts, libs/web-components/data-table/src/data-table.ts, libs/web-components/data-table/src/model.ts, libs/web-components/data-table/src/utils.ts, libs/web-components/data-table/stories/data-table-with-pagination.stories.ts, libs/web-components/data-table/stories/data.ts
1. possible to disable selection for certain rows.
2. keep selection cross pages for fds-data-table-with-pagination component
=> feat(data-table): data table new feature 

libs/web-components/textfield/src/base-textfield.ts
=> fix(textfield): correct handling for date picking

libs/web-components/charts/README.md, libs/web-components/charts/demo/index.html, libs/web-components/charts/package.json, libs/web-components/charts/src/apexcharts.ts, libs/web-components/charts/src/index.ts, libs/web-components/charts/src/line-chart-styles.scss, libs/web-components/charts/src/line-chart.ts, libs/web-components/charts/stories/line-charts.stories.ts, libs/web-components/charts/stories/pie-charts.stories.ts, libs/web-components/charts/test/charts.test.ts
=> feat(wc:line-chart): initial implementation 

.changeset/brown-mangos-pump.md, libs/web-components/app-card/README.md, libs/web-components/app-card/demo/index.html, libs/web-components/app-card/stories/app-card.stories.ts, libs/web-components/chip/src/styles.scss
Before:
'api' => 'API'
After: 
'api' => 'Api'
'API' => 'API'
=> fix(fds-chip): capitalize only first letter of chips label

README.md, libs/web-components/chip/demo/index.html, libs/web-components/chip/src/styles.scss, libs/web-components/chip/stories/chip.stories.ts, package-lock.json
=> fix spacings for chips

packages/fds-components-web/guided-tour/src/guided-tour.ts
Fix for the CodeQL issue described in #1080
=> test for regular expression fix

package-lock.json, packages/fds-components-web/charts/src/bar-chart.ts, packages/fds-components-web/sparkline/.eslintrc.json, packages/fds-components-web/sparkline/.npmignore, packages/fds-components-web/sparkline/README.md, packages/fds-components-web/sparkline/demo/index.html, packages/fds-components-web/sparkline/package.json, packages/fds-components-web/sparkline/src/sparkline.ts, packages/fds-components-web/sparkline/src/styles.scss, packages/fds-components-web/sparkline/stories/sparkline.stories.ts, packages/fds-components-web/sparkline/test/sparkline.test.ts, packages/fds-components-web/sparkline/tsconfig.json, packages/fds-components-web/tsconfig.json
Displaying a mini, colorful linechart from an array of values.
fix #1027
=> 💥 New sparkline component
