Finastra/finastra-design-system

- .github/CODEOWNERS
As documented in Github [here](https://help.github.com/en/articles/about-code-owners), we can request review from owners of some files / folders of a repo.
Just testing the feature at the moment before adding more owners.
> feat(github): add CODEOWNERS file to enforce reviews by owners

- themes/angular-theme/lib/button/_button-theme.scss
Removed gradient used before creating $uxg-gradient in [palette](https://github.com/fusionfabric/finastra-design-system/blob/master/themes/angular-theme/lib/core/theming/_palette.scss#L137).
> fix(button): remove unused variable in button theme

- .github/CODEOWNERS
- apps/angular-test-app/src/app/app-routing.module.ts
- apps/angular-test-app/src/app/app.component.html
- apps/angular-test-app/src/app/app.component.scss
- apps/angular-test-app/src/app/app.component.ts
- apps/angular-test-app/src/app/app.module.ts
- apps/angular-test-app/src/app/components/home/home.component.html
- apps/angular-test-app/src/app/components/home/home.component.scss
- apps/angular-test-app/src/app/components/popover-demo/popover-demo.component.html
- apps/angular-test-app/src/app/components/popover-demo/popover-demo.component.scss
- apps/angular-test-app/src/app/components/popover-demo/popover-demo.component.spec.ts
- apps/angular-test-app/src/app/components/popover-demo/popover-demo.component.ts
- apps/angular-test-app/src/app/routes.ts
- apps/angular-test-app/src/styles.scss
- libs/angular-components/components.module.ts
- libs/angular-components/popover/ng-package.json
- libs/angular-components/popover/package.json
- libs/angular-components/popover/src/_popover.theme.scss
- libs/angular-components/popover/src/index.ts
- libs/angular-components/popover/src/popover.component.html
- libs/angular-components/popover/src/popover.component.spec.ts
- libs/angular-components/popover/src/popover.component.ts
- libs/angular-components/popover/src/popover.module.spec.ts
- libs/angular-components/popover/src/popover.module.ts
- tsconfig.json
Simple popover based on mat-menu (Material doesn't offer such widget by default)
You can configure x- and y- positions and apply a css class for the panel (to change max-width for example), and of course provide the content as a template.
> feat(popover): add component + cleanup

- themes/angular-theme/lib/card/_card-base.scss
It works only for a horizontal list of cards, not on grids.
Here is the shift generated by the margin-left on grids:
> fix(card): remove margin-left on card+card. 

- themes/angular-theme/lib/core/typography/_typography.scss
Since Futura is licensed font, we need to provide alternatives for people not buying it.
1. We first try to load Futura from different foundries (if loaded or installed on client)
`Futura EF` - `Futura PT` - `Futura`
2. Then we try an open font from Google
`Hind`
3. Then we load closest looking system fonts
`Verdana` - `Arial Black`
4. Finally we use generic font family name
`sans-serif`
> fix(typography): add more and better fallback fonts for Futura

- apps/angular-test-app/src/app/app-routing.module.ts
- apps/angular-test-app/src/styles.scss
- libs/angular-components/global-search/src/global-search.component.scss
- libs/angular-components/popover/src/popover.component.scss
- libs/angular-components/popover/src/popover.component.ts
- libs/angular-components/table/src/table.component.scss
- tools/schematics/angular-component/files/src/__filename__.component.scss.template
- tools/schematics/angular-component/files/src/__scssFilename__.theme.scss.template
- tools/schematics/angular-component/index.ts
In order for the components to contain their styles we will need to do this in the component main scss
1. import the `uxg-app-theme`
2. import the `component-theme`
3. use the component mixin
Example from the global-search component:
```scss
@import '../../../../themes/angular-theme/uxg-app-theme';
@import './global-search.theme';
@include uxg-global-search-theme($uxg-light-theme);
```
I have updated the component schematic with these new changes.
**NOTE 1:** Components that do not require theming, need not use this.
**NOTE 2:** Relative pathing to the `uxg-app-theme` did not work
**NOTE 3:** In order to allow themes we will need to refactor all the components and the theme. 
We will neeed to import `_component.theme.scss` into the `uxg-angular-theme` and build it there two times for both …
> feat(bundle): properly bundle all css

- themes/angular-theme/lib/core/typography/_typography.scss
Apply `uxg-body-1` on `<p>` by default when using class .uxg-typography on body.
> fix(typography): apply body-1 on paragraphs by default

- themes/angular-theme/lib/core/typography/_typography.scss
Styling on p is much stronger than styling on class.
As a result it overrides every other styles (uxg-subtitle / uxg-display / ...) including the ones in other ui-elements.
where it is acceptable to have default headlines styles, it is not on paragraph since it can be used for many other usages (display / subtitle / body / ...)
The best strategy is to have lighter styling level possible on typography, which is class level only.
> fix(typography): remove default uxg-body-1 on paragraph

- themes/angular-theme/lib/badge/_badge-base.scss
- themes/angular-theme/lib/badge/_badge-theme.scss
Closes #43 
Large side badges are now properly rendered in similar style to medium ones.
> feat(badge-styles): add large side badges

- libs/angular-components/filter/filter-tree/src/filter-tree.component.html
Bug: when a parent node has the same label as a child node the divider is not displayed.
> bugfix(filter-tree): fixed tree-divider rendering condition

- themes/angular-theme/lib/list/_list-base.scss
- themes/angular-theme/lib/list/_list-theme.scss
Result:
Usage with `<ol>`:
```html
<ol class="uxg-ol">
<li>
<h5 class="uxg-ol-title">Item one</h5>
<p class="uxg-body-1">Some text under the title of the ordered list.</p>
</li>
<li>anything without tag</li>
<li>
<p class="uxg-subtitle-3">test with p as subtitle-3</p>
<p class="uxg-subtitle-3">test with p as subtitle-3</p>
</li>
</ol>
```
Usage with `<section>`:
```html
<div class="uxg-ol">
<section>
<h5 class="uxg-ol-title">First step</h5>
<p class="uxg-body-1">Some text under the title of the ordered list.</p>
</section>
<section>
<h5 class="uxg-ol-title">Second step</h5>
<p class="uxg-body-1">Some more content</p>
</section>
</div>
```
> feat(list): implement ordered list

- themes/angular-theme/lib/core/style/_elevation.scss
- themes/angular-theme/lib/core/theming/_palette.scss
get closer to design specifications in Sketch file.
01dp card's elevation:
> fix(elevation): fix low contrast on cards border

- apps/angular-test-app/src/app/app.component.html
- apps/angular-test-app/src/app/app.component.scss
- apps/angular-test-app/src/app/app.component.spec.ts
- apps/angular-test-app/src/app/app.component.ts
Add a checkbox to switch to dark theme.
It reveals some components are not theme ready.
> feat(app): enable dark theme in test app

- themes/angular-theme/lib/button/_button-base.scss
- themes/angular-theme/lib/icon/_icon-base.scss
mat-icon-button, when clicked in IE11, was displaying a crocked display. Now the icon is centered again.
> fix(icon-button): fixed icon-button behaviour when clicked in IE11

- themes/angular-theme/lib/logo/_logo-base.scss
Fix #171, when we use `<a>` tag without `href` parameter we still need the pointer cursor. It's very common in Angular when using `RouterLink` or `(click)` to trigger action or navigation.
> fix(logo): force pointer cursor when logo used as a link

- .github/workflows/release.yml
Moved the release from Azure DevOps to Githb Actions.
Steps on how to release:
1. commit to master `chore(release): prepare for VERSION release`
2. create release tag
And the workflow should start and do the release :)
Note:
Now that we are quite happy with the contents, we can stop doing pre-releases.
> chore(config): added release workflow

- themes/angular-theme/package.json
- tools/devkit/builders/theme/theme-builder.ts
According to FDS documentation, import should look like this
```SCSS
@import '~@ffdc/uxg-angular-theme/all-theme';
```
Which is fine for an Angular SASS project but not compatible with a project running `ng new` choosing CSS for styling and trying to import `_all-theme.css`
> fix(config): import should be the same for css and sass

- apps/angular-test-app/src/app/components/global-nav-demo/global-nav-demo.component.ts
- libs/angular-components/cards/account-card/README.md
- libs/angular-components/global-nav/src/_variables.scss
- libs/angular-components/global-nav/src/components/navbar/navbar.component.html
- libs/angular-components/global-nav/src/components/navbar/navbar.component.scss
- libs/angular-components/global-nav/src/components/navbar/navbar.component.ts
- libs/angular-components/global-nav/src/global-nav.component.html
- libs/angular-components/global-nav/src/global-nav.component.spec.ts
- libs/angular-components/global-nav/src/global-nav.component.ts
- libs/angular-components/global-nav/src/services/navigation.model.ts
If no `currentNode` is specified, it will try to infer it from the router.
Ideal setup :
`constants.ts`
```ts
export const routes = [
{
path: '',
loadChildren: () => import('./home/home.module').then((m) => m.HomeModule),
icon: 'home',
title: 'Home',
tooltip: 'Home',
},
];
```
`app.routing.module.ts`
```ts
import { NgModule } from '@angular/core';
import { Routes, RouterModule } from '@angular/router';
import { AppComponent } from './app.component';
import { routes } from './constants';
@NgModule({
imports: [
RouterModule.forChild([
{
path: '',
component: AppComponent,
children: routes,
},
]),
],
exports: [RouterModule],
})
export class AppRoutingModule {}
```
`app.component.ts`
```ts
import { Component, OnInit } from '@angular/core';
import { routes } from './constants';
import { Router, …
```
> fix(global-nav): Display current node in navbar

- CONTRIBUTING.md
document the use of add-component schematic when creating a component for @ffdc/uxg-angular-components
> fix(doc): add reference to add-component schematic

- libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay-config.ts
- libs/angular-components/global-search/src/components/global-search-overlay/global-search-overlay.component.ts
- libs/angular-components/global-search/src/global-search.component.ts
- libs/angular-components/global-search/src/services/global-search-overlay.service.ts
Removed the exposed search icon from global search and changed the names of the output to respect Angular conventions
> feat(global-search): improvements++

- apps/angular-test-app/src/app/components/user-profile-menu-demo/user-profile-menu-demo-component.component.html
- libs/angular-components/user-profile-menu/index.ts
- libs/angular-components/user-profile-menu/src/user-profile-menu.component.html
- libs/angular-components/user-profile-menu/src/user-profile-menu.component.ts
- libs/angular-components/user-profile-menu/src/user-profile-menu.module.ts
- libs/angular-components/user-profile-menu/src/user-profile-panel-details.directive.ts
- libs/angular-components/user-profile-menu/src/user-profile-panel.component.html
- libs/angular-components/user-profile-menu/src/user-profile-panel.component.ts
added details under user name and email to user-profile-menu
> feat(user-profile-menu): added details

- themes/angular-theme/lib/table/_table-base.scss
> fix(table): display flex only on div immediate child of <th>

- .github/workflows/pr-build.yml
- themes/angular-theme/lib/button/_button-theme.scss
> fix(button): improve flat-button focus

- libs/angular-components/package.json
- themes/angular-theme/package.json
Hopefully fix :
See for yourselves : https://github.com/fusionfabric/finastra-design-system/network/dependents
As compared to : https://github.com/angular/angular/network/dependents
> chore: Specify repository for packages to get insights about dependents

- themes/angular-theme/lib/card/_card-theme.scss
now text color adapts to the theme (white text on dark theme and dark text on light theme)
fix #309
> fix(card): adapt product card text color to theme

- themes/angular-theme/lib/button-toggle/_button-toggle-base.scss
border radius can be set even when toggle button is not checked.
Make it easier for people using border style to display focus state.
fix #314
> fix(toggle-button): remove useless selector

- themes/angular-theme/lib/core/typography/_all-typography.scss
Form-field typography was not imported in theme ¯\_(ツ)_/¯
> fix(theme): add missing import of form-field typography

- themes/angular-theme/lib/button/_button-base.scss
Add subtle hover state on icon-button.
similar to what's already applied on default mat-button.
fix #290
> feat(icon-button): add hover state

- libs/angular-components/global-search/src/_global-search.theme.scss
Global search close button was always dark.
Now it's following foreground text color (dark in light theme, light in dark theme)
> fix(global-search): make global search compatible with dark theme

- apps/angular-test-app/src/app/components/wizard-demo/wizard-demo.component.html
- apps/angular-test-app/src/app/components/wizard-demo/wizard-demo.component.scss
- libs/angular-components/wizard/src/wizard.component.html
- libs/angular-components/wizard/src/wizard.component.scss
⚠️ **To review carefully, making sure it won't affect apps already using it.**
Use % for sizing and positioning over vw and vh units.
Allow to use the wizard in a smaller container instead of full screen all the time.
> feat(wizard): sizing over container instead of viewport

- apps/angular-test-app/src/styles.scss
- libs/angular-components/wizard/src/_wizard.theme.scss
loading typography inside wizard theme causes a reload of @angular/material/theming which then load the mat-color() mixin again which override our own override that helps handling CSS vars.
> fix(wizard): remove not necessary import to prevent css var bug

- themes/angular-theme/_all-theme.scss
- themes/angular-theme/_dark.scss
- themes/angular-theme/lib/core/theming/_all-theme.scss
- themes/angular-theme/lib/core/theming/_palette.scss
Simplify the way you include the theme
You don't necessarily need to use `.uxg-dark-theme` anymore.
If you load only dark theme you can do:
```SCSS
@include uxg-material-theme($uxg-dark-theme);
```
If you load dark theme by default and switch with a custom class:
```SCSS
@include uxg-material-theme($uxg-dark-theme);
.any-class-you-want {
@include uxg-material-theme($uxg-light-theme);
}
```
if you want to use user prefered color scheme then:
```SCSS
@include uxg-material-theme($uxg-light-theme);
@media (prefers-color-scheme: dark) {
@include uxg-material-theme($uxg-dark-theme);
}
```
> feat(theme): simplify theme inclusion

- themes/angular-theme/lib/core/theming/_all-theme.scss
> fix(theme): force text contrast on selection

- themes/angular-theme/lib/icon/_icon-theme.scss
Currently when you use SASS theme and your app does not run autoprefixer, you end up with gradient icons like this:
It's already happening on some StackBlitz examples.
Adding prefix manually ensure user will have correct rendering even if he is not using any auto-prefixing tool.
> fix(icon): gradient without autoprefixer

- apps/angular-test-app/src/app/components/global-nav-demo/global-nav-demo.component.html
- apps/angular-test-app/src/app/components/global-nav-demo/global-nav-demo.component.ts
- libs/angular-components/global-nav/src/components/sidenav/sidenav.component.ts
- libs/angular-components/global-nav/src/global-nav.component.html
- libs/angular-components/global-nav/src/global-nav.component.ts
New feature for the global-nav 🥳
* add _shortName_ input to force the _iconName_ in the product card component, but why ?? For example Malauzai short name is MZL.
* add a limit for long _iconName_ without whitespace.
> feat(global-nav): add optional shortName

- .github/CODEOWNERS
following discussion #369
Replacing @studio-team by @dorsaffrigui and I
Adding @adrian-apetrei to backup @rbordeanu on repo management
> chore(codeowners): replace studio team and add repo owners

- themes/angular-theme/lib/avatar/_avatar-theme.scss
- themes/angular-theme/lib/badge/_badge-theme.scss
- themes/angular-theme/lib/breadcrumb/_breadcrumb-theme.scss
- themes/angular-theme/lib/button-toggle/_button-toggle-theme.scss
- themes/angular-theme/lib/button/_button-theme.scss
- themes/angular-theme/lib/card/_card-theme.scss
- themes/angular-theme/lib/chips/_chips-theme.scss
- themes/angular-theme/lib/core/theming/_palette.scss
- themes/angular-theme/lib/core/theming/_theming.scss
- themes/angular-theme/lib/expansion/_expansion-theme.scss
- themes/angular-theme/lib/form-field/_form-field-theme.scss
- themes/angular-theme/lib/list/_list-theme.scss
- themes/angular-theme/lib/table/_table-theme.scss
Remove trailing slash in @use statement of angular-material.
Looks like it's not appreciated by Stackblitz.
> refactor(theme): remove angular material @use trailing slash

- apps/fds-test-app/src/index.html
- apps/fds-test-app/src/styles.scss
- themes/fds-theme/typography/README.mdx
- themes/fds-theme/typography/_mixins.scss
- themes/fds-theme/typography/_variables.scss
To be consistent with spacing and elevation that are written with dash numbers like so:
fds-spacing-1 or fds-elevation-2
We are changing typo names to include dash as well:
previously fds-headline2 -> now fds-headline-2
> fix(fds): change typo names with dash

- themes/fds-theme/typography/_mixins.scss
fallback value for typo custom properties was not including Roboto by default.
> fix(fds): add roboto as default font for typo

- scripts/wca-to-storybook.js
Issue happened whenever we worked on a branch with a new component and switched back to a branch without this component. Leftover custom-elements.json that were already transformed were wrongly picked up by the script.
> fix(wca-to-storybook): Fix issue with leftover custom-elements.json

- libs/angular-components/changelog/src/_changelog.theme.scss
Using `primary`, `secondary`, `success` and `error` from theme instead of palette.
fix #567
> feat(changelog): use semantic colors from theme

- tools/generators/web-component/index.ts
`npm run wc:generate fds-button` will generate web-components/button instead of web-components/fds-button.
Same for a file name that starts with fds like fdsButton.
> fix(wc-generator): remove 'fds' from the generated file name

- .storybook/preview-head.html
Fix incorrect alignment of icon in storybook render
> fix(fds-button): icon vertical align in storybook

- libs/web-components/textfield/demo/index.html
- libs/web-components/textfield/src/styles.scss
- libs/web-components/textfield/src/textfield.ts
- libs/web-components/textfield/stories/textfield.stories.ts
Implement new textfield design:
> feat(textfield): apply v2 design

- apps/angular-test-app/src/app/components/ui-elements-demo/ui-elements-demo.component.html
- themes/angular-theme/lib/form-field/_form-field-base.scss
- themes/angular-theme/lib/form-field/_form-field-theme.scss
Only adding text field: label inside, normal and dense sizes.
Should not affect v1 "fill" appearance, developers needs to opt-in by specifying `appearance="outline"`
> feat(textfield): applying v2 outline style

- themes/angular-theme/lib/form-field/_form-field-theme.scss
see error background going outside the outlined border on the top side of the textfield:
> fix(form-field): error background too large for appearance outline

- libs/web-components/global-nav/README.md
- package-lock.json
- themes/fds-theme/package.json
1. remove `npm i @material/mwc-drawer` from global-nav readme since it already installs `@finastra/sidenav`
2. move `@material/elevation` as a dependency instead of peerDependency from `@finastra/fds-theme`
> feat(theme): move elevation as dependency

- libs/web-components/button/src/base-button.ts
After refactoring of the `fds-button`, those properties are no longer required.
`text`, `unelevated`, `outline`.
> fix(button): remove text, unelevated, outline props

- themes/angular-theme/lib/core/theming/_palette.scss
> fix(angular-theme): :pencil2: Fix typo for crimson palette

- libs/web-components/icon-bar/demo/index.html
- libs/web-components/icon-bar/package.json
- libs/web-components/icon-bar/src/icon-bar-item.ts
fix #898
tippy and popperjs are not direct dependencies of this component, we offer possibility to use it but it's not referenced directly in the component.
> fix(icon-bar): add necessary dependencies

- angular.json
- libs/web-components/checkbox/stories/checkbox.stories.ts
- libs/web-components/filter-tree/package.json
- libs/web-components/filter-tree/src/tree-item/tree-item.ts
- libs/web-components/formfield/.eslintrc.json
- libs/web-components/formfield/.npmignore
- libs/web-components/formfield/README.md
- libs/web-components/formfield/demo/index.html
- libs/web-components/formfield/package.json
- libs/web-components/formfield/src/formfield.ts
- libs/web-components/formfield/src/styles.scss
- libs/web-components/formfield/stories/formfield.stories.ts
- libs/web-components/formfield/test/formfield.test.ts
- libs/web-components/formfield/tsconfig.json
- libs/web-components/radio/stories/radio.stories.ts
- libs/web-components/switch/src/styles.scss
- libs/web-components/switch/stories/switch.stories.ts
- libs/web-components/tsconfig.json
To be able to have labels next to checkbox, radio and switch :  
```
<fds-formfield label="Accept terms and conditions">
<fds-checkbox checked></fds-checkbox>
</fds-formfield>
```
> feature(wc): fds formfield

- packages/fds-components-web/badge/src/badge.ts
- packages/fds-components-web/badge/src/styles.scss
When the badge is of type `none` and it doesn't have a value, there's the border shadow showing up:
This PR fixes that issue:
> fix for empty value badge

- .stylelintrc.json
- packages/fds-theme-web/color/_mixins.scss
- packages/fds-theme-web/color/color.stories.mdx
```SCSS
@include fds.background(primary, $important: true);
// OR
@include fds.background(primary, true);
```
will result in:
```SCSS
background: var(--fds-primary, #694ED6) !important;
```
> Theme: Support important flag in mixins
